tools: Remove unnecessary import statement for GLib
The make_schema.py tool is not using GLib, nor importing data that
requires the GLib introspection API.

This causes a build failure in Continuous:

  File "../tools/make_schema.py", line 3, in <module>
        from gi.repository import GLib
from gi.repository import GLib
ImportErrorImportError: : No module named gi.repository
No module named gi.repository