Use GLib, GObject from gi.repository instead of glib, gobject
Use GLib and GObject from gi.repository instead of glib and gobject
modules for compatibility with pygobject-3.0. Otherwise, when running on
a system with pygobject-2.0 and pygobject-3.0 installed, caribou-preferences
fails with

ImportError: could not import gobject (error was: ImportError('When
using gi.repository you must not import static modules like "gobject".
Please change all occurrences of "import gobject" to "from gi.repository
import GObject".',))

https://bugzilla.gnome.org/show_bug.cgi?id=657666